test:
  capture:
    model: 'TestUser'
    controller: 'session'
    client_id: 'kjhgkjhgdw7qd8qw873yrgukegw'
    client_secret: 'sssshh-dont-tell-anyone'
    domain: 'https://asite.dev.janraincapture.com'
    redirect_url: 'http://mysite.com/auth'
    within_iframe: true
    entity:
      # see the rails_setup migration for field information
      ignore_columns: [ 'aboutMe' ] # external names
      mappings: # external: 'internal'
        birthday: 'birthdate'
        aboutMe: 'about_me' # note: even though about me is ignored, it still needs to be mapped so conversion from active record to capture works
        displayName: 'display_name'

