test:
  capture:
    model: 'TestUser'
    controller: 'session'
    client_id: 'kjhgkjhgdw7qd8qw873yrgukegw'
    client_secret: 'sssshh-dont-tell-anyone'
    domain: 'https://asite.dev.janraincapture.com'
    redirect_url: 'http://mysite.com/auth'
    within_iframe: true
    entity:
      # see the rails_setup migration for field information
      ignore_columns: [ 'aboutMe' ]
      mappings:
        birthday: 'birthdate'

